name: Tests and Coverage

on: pull_request

env:
  HOST_NAME: "http://localhost:4000/"

jobs:
  tests_and_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        elixir: [1.14]
        otp: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v1
        id: mix-cache-test
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp}}-%{{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix depencies
        if: steps.mix-cache-test.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix ecto.create
      - name: ====> test
        run: mix coveralls.html
    services:
      pg:
        image: postgres:12
        ports: ["5432:5432"]
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
